apiVersion: apps/v1
kind: Deployment
metadata:
  name: gomegle
  namespace: gomegle
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gomegle
  template:
    metadata:
      labels:
        app: gomegle
    spec:
      containers:
        - name: gomegle
          image: ghcr.io/johan253/gomegle:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: gomegle-env
          ports:
            - containerPort: 23234
              name: tcp
              protocol: TCP
          volumeMounts:
            # Mount private key secret
            - name: ssh-hostkey
              mountPath: /app/.ssh/id_ed25519
              subPath: id_ed25519
              readOnly: true
            # Mount public key secret
            - name: ssh-hostkey
              mountPath: /app/.ssh/id_ed25519.pub
              subPath: id_ed25519.pub
              readOnly: true
      volumes:
        - name: ssh-hostkey
          secret:
            secretName: gomegle-ssh-hostkey
            defaultMode: 0600
---
apiVersion: v1
kind: Service
metadata:
  name: gomegle
  namespace: gomegle
spec:
  selector:
    app: gomegle
  ports:
    - port: 23234
      targetPort: 23234
      name: tcp
      protocol: TCP
