apiVersion: apps/v1
kind: Deployment
metadata:
  name: gomegle-web
  namespace: gomegle
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gomegle-web
  template:
    metadata:
      labels:
        app: gomegle-web
    spec:
      containers:
        - name: gomegle-web
          image: ghcr.io/johan253/gomegle-web:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: gomegle-env
          env:
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: gomegle-web
  namespace: gomegle
spec:
  selector:
    app: gomegle-web
  ports:
    - port: 3000
      targetPort: 3000
